### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by karopyszcz** [salesforce-marketingcloud/FuelSDK-Java#65] opened 2017-11-09 11:06 UTC
I installed it with a maven dependency and I got an old version. ETDataExtension doesn't contain SendableSubscriberField and SendableDataExtensionField. Please update it.

**Comment by karopyszcz** [comment] 2017-11-09 11:11
Furthermore, there is no .jar file in Release page for newest versions...

**Comment by sharif26** [comment] 2017-11-09 14:27
Thanks for raising the issue.
Did you get the new version 1.2.1 by mentioning in pom.xml file:
```
<dependency>
  <groupId>com.github.salesforce-marketingcloud</groupId>
  <artifactId>fuelsdk</artifactId>
  <version>1.2.1</version>
</dependency>
```
About jar file, we are working on it to release it soon.

**Comment by karopyszcz** [comment] 2017-11-09 14:30
@sharif26 Yes, I used the newest version

**Comment by sharif26** [comment] 2017-11-09 14:34
jar file uploaded in the release tab.

**Comment by sharif26** [comment] 2017-11-09 16:36
@karopyszcz I pushed again to the maven repo and checked in the source jar file that those two fields are there.
could you please try to get the jar again and test it. If still does not work, then please get the source jar using below pom.xml dependency config:

```
<dependency>
  <groupId>com.github.salesforce-marketingcloud</groupId>
  <artifactId>fuelsdk</artifactId>
  <version>1.2.1</version>
  <classifier>sources</classifier>
</dependency>
```

**Comment by karopyszcz** [comment] 2017-11-13 14:28
@sharif26 Thanks, now the maven dependency works well. 

Could you also tell me if it is possible to connect and send internal objects with this sdk instead of ET-ones?

**Comment by karopyszcz** [comment] 2017-12-14 15:43
I am writing once again, because 1.2.2 doesn't exists on maven, and even 1.2.1 seems to be outdated. I wanted to switch from .jar you provided and many classes are missing.

**Comment by sharif26** [comment] 2018-01-11 19:32
Thanks for notifying us the issue.
For some reason, the repo is not correctly pushed from oss sonatype (https://oss.sonatype.org/) to maven repo(http://repo.maven.apache.org/maven2/) when we released.
And we checked on oss sonatype repo, but did not check on the maven repo from where the dependencies are actually downloaded.
The issue is fixed, thanks for your patience, please let us know if we face any difficulty using the new version.

**Closed by sharif26** 2018-01-11 19:32 UTC
